In [1]:
import pandas as pd
import numpy as np

In [2]:
s1 = pd.Series([4,7,-5,3])#创建一个series，索引为默认值

In [3]:
print(s1)

0    4
1    7
2   -5
3    3
dtype: int64


In [4]:
s1.values#serise的值

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
s1.index#series的索引

RangeIndex(start=0, stop=4, step=1)

In [6]:
s2 = pd.Series([4.0,6.5,-0.5,4.2],index = ['d','b','a','c'])#更改索引值
print(s2)

d    4.0
b    6.5
a   -0.5
c    4.2
dtype: float64


In [7]:
s2['a']#根据索引取值

-0.5

In [8]:
s2[['a','b','c']]#多个索引同时取值

a   -0.5
b    6.5
c    4.2
dtype: float64

In [9]:
'b' in s2

True

In [10]:
'e' in s2

False

In [11]:
#Serises可以看成是一个定长的有序字典
dic1 = {'apple':5,'pen':3,'applepen':10}#字典是无序的
s3 = pd.Series(dic1)

In [12]:
print(s3)

apple        5
pen          3
applepen    10
dtype: int64


In [13]:
#DataFrame
data = {'year':[2014,2015,2016,2017]
       ,'income':[10000,30000,50000,80000]
       ,'pay':[5000,20000,30000,30000]
       }

df1 = pd.DataFrame(data)
print(df1)

   year  income    pay
0  2014   10000   5000
1  2015   30000  20000
2  2016   50000  30000
3  2017   80000  30000


In [14]:
df1

year  income    pay
0  2014   10000   5000
1  2015   30000  20000
2  2016   50000  30000
3  2017   80000  30000

In [15]:
df2 = pd.DataFrame(np.arange(12).reshape((3,4)))
df2

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [16]:
df3 = pd.DataFrame(np.arange(12).reshape((3,4)),index = ['a','b','c'],columns=[2,33,44,5])
df3

2   33  44  5 
a   0   1   2   3
b   4   5   6   7
c   8   9  10  11

In [17]:
df1.columns

Index(['year', 'income', 'pay'], dtype='object')

In [18]:
df1.index

RangeIndex(start=0, stop=4, step=1)

In [19]:
df1.values

array([[ 2014, 10000,  5000],
       [ 2015, 30000, 20000],
       [ 2016, 50000, 30000],
       [ 2017, 80000, 30000]], dtype=int64)

In [20]:
df3.columns

Int64Index([2, 33, 44, 5], dtype='int64')

In [21]:
df3.index

Index(['a', 'b', 'c'], dtype='object')

In [22]:
df3.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
df1.describe()

year        income           pay
count     4.000000      4.000000      4.000000
mean   2015.500000  42500.000000  21250.000000
std       1.290994  29860.788112  11814.539066
min    2014.000000  10000.000000   5000.000000
25%    2014.750000  25000.000000  16250.000000
50%    2015.500000  40000.000000  25000.000000
75%    2016.250000  57500.000000  30000.000000
max    2017.000000  80000.000000  30000.000000

In [24]:
df1.T

0      1      2      3
year     2014   2015   2016   2017
income  10000  30000  50000  80000
pay      5000  20000  30000  30000

In [25]:
df3.sort_index(axis = 1)#列排序

2   5   33  44
a   0   3   1   2
b   4   7   5   6
c   8  11   9  10

In [26]:
df3.sort_index(axis = 0)

2   33  44  5 
a   0   1   2   3
b   4   5   6   7
c   8   9  10  11

In [27]:
df3.sort_values(by=44)#对44列进行排序,这里默认了axis = 0

2   33  44  5 
a   0   1   2   3
b   4   5   6   7
c   8   9  10  11

In [28]:
df3.sort_values(by= 'a',axis = 1)#当axis = 1时 ，可以对行进行排序

2   33  44  5 
a   0   1   2   3
b   4   5   6   7
c   8   9  10  11