In [1]:
import numpy as np

In [2]:
array = np.array([[1,2,3],
                  [4,5,6],
                  [6,7,8]])

In [3]:
print(array)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [4]:
print(array.ndim) #矩阵维度

2


In [5]:
print(array.shape)#矩阵形状

(3, 3)


In [6]:
print(array.size)#矩阵大小

9


In [7]:
print(array.dtype)#矩阵中元素类型

int32
