In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3],dtype=np.int32)
print(a.dtype)

int32


In [3]:
b = np.array([1,2,3],dtype=np.float)
print(b.dtype)

float64


In [4]:
print(b)

[1. 2. 3.]


In [5]:
c = np.array([1,2,3]) #一维数据
print(c)

[1 2 3]


In [6]:
d =  np.array([[1,2,3]
               ,[4,5,6]]
             )#二维矩阵

In [7]:
print(d)

[[1 2 3]
 [4 5 6]]


In [8]:
d.ndim

2

In [9]:
c.ndim

1

In [12]:
zero = np.zeros((2,3))#生成2行3列的零矩阵
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
one = np.ones((3,4)) #生成3行4列的全为1的矩阵
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
empty = np.empty((2,3))#生成的这个矩阵 里面的元素不是零 而是无穷小 是接近于零的数

In [16]:
print(empty)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
e = np.arange(10)

In [18]:
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
f = np.arange(3,45) #排列

In [24]:
print(f)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]


In [25]:
g = np.arange(3,45,2)#3到45的排列，步数为2

In [27]:
print(g)

[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43]


In [28]:
h = np.arange(8).reshape(2,4)#转化为2行4列的矩阵 ，重新定义矩阵的形状
print(h)

[[0 1 2 3]
 [4 5 6 7]]


In [29]:
i = np.arange(8).reshape(4,2)
print(i)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
