In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3]
                ,[4,5,6]
                ,[7,8,9]])
arr2 = np.array([[9,8,7]
                ,[6,5,4]
                ,[3,2,1]])
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [3]:
print(arr1+arr2)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [4]:
print(arr2 - arr1)

[[ 8  6  4]
 [ 2  0 -2]
 [-4 -6 -8]]


In [5]:
print(arr1 * arr2) #按位相乘

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [6]:
print(arr1 ** arr2) #按位取幂

[[   1  256 2187]
 [4096 3125 1296]
 [ 343   64    9]]


In [7]:
print(arr1 / arr2) #按位相除

[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [8]:
print(arr1 // arr2) #按位相除后 取整

[[0 0 0]
 [0 1 1]
 [2 4 9]]


In [9]:
print(arr1 + 2 )

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [10]:
print(arr1 * 10)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [11]:
arr3 = arr1 > 3
print(arr3)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [13]:
np.dot(arr1 , arr2) #矩阵乘法

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [14]:
arr1.dot(arr2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [15]:
print(arr1)
print(arr1.T)
print(np.transpose(arr1)) #矩阵转置

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
