In [2]:
import numpy as np

In [3]:
sample1 = np.random.random((3,2)) #生成3行2列的随机数 范围是0到1
print(sample1)

[[0.46934683 0.75348746]
 [0.01148764 0.33318979]
 [0.56922875 0.970739  ]]


In [4]:
sample2 = np.random.normal(size = (3,2)) #生成3行2列符合标准正态分布的随机数
print(sample2)

[[ 0.68008415  0.81335826]
 [ 0.50236721 -0.68590259]
 [ 1.70441412 -0.0026633 ]]


In [5]:
sample3 = np.random.randint(0,10,size = (3,2))
print(sample3)

[[5 8]
 [1 8]
 [9 8]]


In [6]:
np.sum(sample1)#求和

3.1074794878259233

In [7]:
np.min(sample2) #求最小值

-0.6859025921031322

In [8]:
np.max(sample3) #求最大值

9

In [9]:
np.sum(sample1,axis = 0) #对列求和

array([1.05006323, 2.05741626])

In [10]:
np.sum(sample1,axis = 1) #对行求和

array([1.2228343 , 0.34467744, 1.53996775])

In [11]:
np.argmin(sample1) #最小值的索引

2

In [12]:
np.argmax(sample1) #最大值索引

5

In [13]:
print(np.mean(sample1))
print(sample1.mean())#求平均值

0.5179132479709873
0.5179132479709873


In [14]:
np.median(sample1) #求中位数

0.5192877934655598

In [15]:
np.sqrt(sample1) #开方

array([[0.68508892, 0.86803656],
       [0.10718043, 0.57722595],
       [0.7544725 , 0.98526088]])

In [16]:
sample4 = np.random.randint(0,16,size = (1,10))
print(sample4)

[[10 15 15  9  7  5  3 11  3 11]]


In [17]:
np.sqrt(sample4)

array([[3.16227766, 3.87298335, 3.87298335, 3.        , 2.64575131,
        2.23606798, 1.73205081, 3.31662479, 1.73205081, 3.31662479]])

In [18]:
np.sort(sample4) #排序

array([[ 3,  3,  5,  7,  9, 10, 11, 11, 15, 15]])

In [19]:
np.sort(sample1) #对每一行进行排序 不是一行的不会排序

array([[0.46934683, 0.75348746],
       [0.01148764, 0.33318979],
       [0.56922875, 0.970739  ]])

In [20]:
np.clip(sample4,2,7) #小于2就变为2 大于7就变为7 控制数值范围

array([[7, 7, 7, 7, 7, 5, 3, 7, 3, 7]])

In [21]:
sample1

array([[0.46934683, 0.75348746],
       [0.01148764, 0.33318979],
       [0.56922875, 0.970739  ]])

In [22]:
sample1.flat

In [23]:
np.sort(sample1.flat)

array([0.01148764, 0.33318979, 0.46934683, 0.56922875, 0.75348746,
       0.970739  ])