In [1]:
import numpy as np

In [2]:
arr1 = np.arange(2,14)
print(arr1)

[ 2  3  4  5  6  7  8  9 10 11 12 13]


In [4]:
print(arr1[2])#提取2号位置的数据

4


In [5]:
print(arr1[1:4])#提取1到4号位置的数据（不包含4号位置的数据）

[3 4 5]


In [7]:
print(arr1[3:-1]) #从第3号到最后一个数据（不包含最后一个数据）

[ 5  6  7  8  9 10 11 12]


In [9]:
print(arr1[:6])#前六个数据

[2 3 4 5 6 7]


In [11]:
print(arr1[2:])#从第二个开始取到结束

[ 4  5  6  7  8  9 10 11 12 13]


In [12]:
arr2 = arr1.reshape(3,4)

In [13]:
arr2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [14]:
arr2[1]

array([6, 7, 8, 9])

In [15]:
arr2[1][1]

7

In [16]:
arr2[1,1]

7

In [19]:
arr2[:,2]#提取所有行的第二列

array([ 4,  8, 12])

In [20]:
for i in arr2: #迭代行
    print(i)#迭代3次（3行）

[2 3 4 5]
[6 7 8 9]
[10 11 12 13]


In [21]:
for i in arr2.T: #使用转置 迭代矩阵的列
    print(i)#迭代4次（4列）

[ 2  6 10]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]


In [22]:
for i in arr2.flat: #使用扁平化 将矩阵拉直 迭代所有元素
    print(i)#迭代12次

2
3
4
5
6
7
8
9
10
11
12
13
