In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [5]:
arr3 = np.vstack((arr1,arr2))#垂直合并

In [7]:
print(arr3)
print(arr3.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [8]:
arr4 = np.hstack((arr1,arr2))#水平合并
print(arr4)
print(arr4.shape)

[1 2 3 4 5 6]
(6,)


In [9]:
arr5 = np.vstack((arr1,arr2,arr3))#多个矩阵合并
print(arr5)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [14]:
arr6 = np.concatenate((arr3,arr5),axis = 0)#axis =0 纵向合并（合并的array维度要相同）

In [15]:
print(arr6)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [17]:
arr7 = np.concatenate((arr3,arr3),axis = 1)#axis =1 水平合并（合并的array维度要相同）
print(arr7)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [18]:
print(arr1.T)#一维的array 不能转置

[1 2 3]


In [20]:
arr1_1 = arr1[np.newaxis,:]#增加维度
print(arr1_1)
print(arr1_1.shape)

[[1 2 3]]
(1, 3)


In [21]:
arr1_1.T

array([[1],
       [2],
       [3]])

In [23]:
arr1_2 = arr1[:,np.newaxis]
print(arr1_2)
print(arr1_2.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [24]:
arr1_2.T

array([[1, 2, 3]])

In [25]:
arr1_3 = np.atleast_2d(arr1)
print(arr1_3)
print(arr1_3.shape)

[[1 2 3]]
(1, 3)
