In [1]:
import numpy as np

In [24]:
#输入数据
#输入数据
X = np.array([[1,0,0]
             ,[1,0,1]
             ,[1,1,0]
             ,[1,1,1]])

#标签
Y = np.array([[0,1,1,0]])
#权值初始化，取值范围-1 到 1

#隐藏层权值（3 * 4）这里的4 可以取值为a ，但不宜过多，也不宜过少
V = np.random.random((3,4)) * 2 -1
#输出层权值（4 * 1）这里的4即就是a值
W = np.random.random((4,1)) * 2 -1

print(V)
print(W)
#学习率设置
lr = 0.11
#迭代次数设置
epoches = 200000

[[-0.77558926 -0.99210872 -0.10423629  0.06053484]
 [-0.12844714 -0.22529773  0.12729164 -0.70947896]
 [-0.76699077 -0.13202151  0.10783271  0.99899518]]
[[-0.94821646]
 [-0.0590847 ]
 [-0.62483441]
 [ 0.79457842]]


In [25]:
#sigmoid函数
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [26]:
#sigmoid函数导数
def dsigmoid(x):
    return x * (1 - x)

In [27]:
#BP神经网络
#所有数据的乘法，theta都是作为乘数，即a * theta 而不能 theta * a 因为a是数据 而theta是给数据乘的权值。
def update(x,y,theta1,theta2,lr,epoches):
    Error = []
    for i in range(epoches):
        
        L1 = sigmoid(np.dot(x , theta1)) #(4 * 4)
        L2 = sigmoid(np.dot(L1 , theta2)) #(4 * 1)
        
        L2_gard = dsigmoid(L2) * (y.T - L2) #( 4 * 1)
        L1_gard = dsigmoid(L1) * np.dot(L2_gard ,theta2.T) #( 4 * 4) 
        
        theta2 = theta2 + lr * np.dot(L1.T , L2_gard)
        theta1 = theta1 + lr * np.dot(x.T  , L1_gard)
        
        if i % 500 == 0 :
            L1 = sigmoid(np.dot(x , theta1)) #(4 * 4)
            L2 = sigmoid(np.dot(L1 , theta2)) #(4 * 1)
            Error.append(np.sum(np.abs(y.T - L2)))
    return theta1,theta2,Error

In [28]:
L1 = sigmoid(np.dot(X , V)) #(4 * 4)
L2 = sigmoid(np.dot(L1 , W)) #(4 * 1)
L2

array([[0.44972882],
       [0.52386857],
       [0.41821911],
       [0.49275793]])

In [29]:
V,W,err = update(X,Y,V,W,lr,epoches)

In [30]:
L1 = sigmoid(np.dot(X , V)) #(4 * 4)
L2 = sigmoid(np.dot(L1 , W)) #(4 * 1)
L2

array([[0.00385521],
       [0.99285324],
       [0.99418159],
       [0.008752  ]])

In [31]:
err

[2.0003806006893106,
 1.98305058755443,
 1.9423129287417205,
 1.811518808000557,
 1.5807088441571422,
 1.3447212758956006,
 0.9700441334526885,
 0.6733413383484711,
 0.5098793118076161,
 0.4142836600782388,
 0.35261747744793154,
 0.3096109660482229,
 0.2778312955571351,
 0.2533082386081066,
 0.2337461171019495,
 0.21772924834310484,
 0.20433785918407138,
 0.19294828876822345,
 0.18312240552573444,
 0.17454311437469455,
 0.1669750364105024,
 0.16023960754227462,
 0.15419878276467064,
 0.1487440631407887,
 0.14378891943229133,
 0.13926344379992378,
 0.13511049919536589,
 0.13128289770287943,
 0.12774129978498117,
 0.12445262762303397,
 0.12138885100087568,
 0.11852604712862351,
 0.11584366461133697,
 0.1133239414273258,
 0.11095144041332876,
 0.10871267534612039,
 0.10659580755167469,
 0.10459039791417768,
 0.10268720276773648,
 0.10087800482065903,
 0.09915547225228549,
 0.09751304062160279,
 0.09594481336629891,
 0.09444547754426935,
 0.09301023214419939,
 0.09163472681686625,
 0.09031