In [4]:
import numpy as np

In [5]:
#输入数据
X = np.array([[1,0,0]
             ,[1,0,1]
             ,[1,1,0]
             ,[1,1,1]])

#标签
Y = np.array([[0,1,1,0]])
#权值初始化，取值范围-1 到 1
V = np.random.random((3,4)) * 2 -1
W = np.random.random((4,1)) * 2 -1
print(V)
print(W)
#学习率设置
lr = 0.11

def sigmoid(x):
    return 1 / (1 + np.exp( -x ))

#sigmoid函数的导数 用自己代表自己时 导数如下：
def dsigmoid(x):
    return x * (1 - x)

def update():
    global X,Y,W,V,lr
    
    L1 = sigmoid(np.dot(X,V)) #隐藏层输出（4，4）
    L2 = sigmoid(np.dot(L1,W)) #输出层输出（4，1）
    
    L2_delta = (Y.T - L2) * dsigmoid(L2)
    L1_delta = L2_delta.dot(W.T) * dsigmoid(L1)
    
    W_C = lr * L1.T.dot(L2_delta)
    V_C = lr * X.T.dot(L1_delta)
    
    W = W + W_C
    V = V + V_C

[[-0.56780344 -0.1262297   0.17762651  0.82497309]
 [-0.38670385 -0.42281363 -0.33609743 -0.91157039]
 [-0.95064522 -0.3784742  -0.08125737  0.82373715]]
[[-0.33328531]
 [-0.40831756]
 [ 0.92785647]
 [ 0.26503236]]


In [6]:
for i in range(20000):
    update() #更新权值
    if i % 500 == 0:
        L1 = sigmoid(np.dot(X,V)) #隐藏层输出（4，4）
        L2 = sigmoid(np.dot(L1,W)) #输出层输出（4，1）
        print('Error:',np.mean(np.abs(Y.T - L2)))

L1 = sigmoid(np.dot(X,V))
L2 = sigmoid(np.dot(L1,W))
print(L2)


Error: 0.5000235219816583
Error: 0.49596643975052335
Error: 0.48745199674553075
Error: 0.46061091869593423
Error: 0.39180455143769244
Error: 0.27803615733625714
Error: 0.18710892213442912
Error: 0.1383986252431922
Error: 0.11110625620601425
Error: 0.09399571705966972
Error: 0.08227448448855385
Error: 0.07371290276947881
Error: 0.0671576142708051
Error: 0.06195674282512538
Error: 0.057714913856204496
Error: 0.05417842692900196
Error: 0.05117689299840526
Error: 0.04859150376886982
Error: 0.04633678446228924
Error: 0.044349593499931686
Error: 0.04258221982366803
Error: 0.04099789993007121
Error: 0.03956781834218526
Error: 0.03826904769457464
Error: 0.03708310127130576
Error: 0.03599489499391461
Error: 0.03499198938859079
Error: 0.03406402690864819
Error: 0.033202308068841266
Error: 0.03239946785174701
Error: 0.0316492256393507
Error: 0.030946189799648013
Error: 0.03028570341338814
Error: 0.02966372132699067
Error: 0.029076711313851367
Error: 0.028521573972863583
Error: 0.02799557732333408